[package]
name = "pruebas_con_premium_reporting_api"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
chrono = "0.4.38"
json = "0.12.4"
reqwest = "0.12.7"
tokio = {version = "1.40.0", features = ["full"] }
